# Student Performance Data Cleaning Project

## Overview

This project focuses on cleaning and preparing a real-world student performance dataset for further analytical exploration using SQL.

The dataset contains several common data quality issues frequently encountered in real analytics projects, including:

- Missing values
- Inconsistent categorical formatting
- Duplicate records
- Incorrect data types
- Potential outliers

The main objective of this notebook is to transform raw and unstructured data into a clean, reliable, and analysis-ready dataset.

---

## Project Workflow

The data cleaning process includes:

1. Importing and exploring the raw dataset
2. Identifying missing values and duplicates
3. Standardizing categorical variables
4. Correcting inconsistent formatting
5. Validating and converting data types
6. Detecting and handling outliers
7. Creating calculated fields
8. Exporting the cleaned dataset for SQL analysis

---

## Technologies Used

- Python
- Pandas
- Jupyter Notebook

---

## Business Context

The dataset simulates student academic information, including:

- Demographics
- Study habits
- Admission exam scores
- Technical subject performance

The cleaned dataset will later be analyzed in SQL to identify:

- Academic performance trends
- Study behavior patterns
- Demographic insights
- Students requiring academic support
- High-performing student groups

---

## Dataset Source

Dataset obtained from Kaggle:

https://www.kaggle.com/datasets/walekhwatlphilip/intro-to-data-cleaning-eda-and-machine-learning

---

## Final Deliverables

This project includes:

- Raw dataset
- Cleaned dataset
- Python data cleaning notebook
- SQL analytical exploration
- Business insights and findings

In [ ]:
# Import the raw dataset and inspect its structure,
# columns, and overall information.

import pandas as pd

data = pd.read_csv("bi.csv", encoding='latin-1')
data.head()
data.tail()
data.shape
# The dataset contains 77 rows and 10 columns.

(77, 11)

In [19]:
# Identify missing values across the dataset.
data.isnull().sum()

# The Python column contains 2 missing values.
# These values will be replaced using the column mean.
data['Python'] = data['Python'].fillna(round(data['Python'].mean(),2))
data.head()
data.isnull().sum()

# Check for duplicate records.
data.duplicated().sum()

np.int64(0)

In [20]:
# Identify inconsistent categorical values across string-based columns.
# Standardize categorical values for Gender, Country, 
# Residence, and Previous Education.

data.gender.unique() #'Female', 'M', 'Male', 'F', 'female', 'male'
genderstd = {'M':'Male',
             'F': 'Female',
             'female':'Female',
             'male': 'Male'}
data['gender'] = data['gender'].replace(genderstd)
data['gender'].unique()

data['country'].unique()
countrystd = {'Rsa':'South Africa',
              'norway':'Norway',
              'Norge':'Norway',
              'UK':'United Kingdom',
              'Somali':'Somalia'}
data['country'] = data['country'].replace(countrystd)
data['country'].unique()

data['residence'].unique() # 'Private',    'Sognsvann', 'BI Residence', 'BI-Residence', 'BIResidence', 'BI_Residence'
residstd = {'BI-Residence':'BI Residence',
            'BIResidence':'BI Residence',
            'BI_Residence':'BI Residence'}
data['residence'] = data['residence'].replace(residstd)
data['residence'].unique()

data['prevEducation'].unique() # 'Masters',  'Diploma',  'HighSchool',  'High School', 'Bachelors', 'Barrrchelors','diploma', 'DIPLOMA', 'Diplomaaa', 'Doctorate'
educstd = {'diploma':'Diploma',
           'Diplomaaa':'Diploma',
           'DIPLOMA':'Diploma',
           'HighSchool':'High School',
           'Barrrchelors':'Bachelors'}
data['prevEducation'] = data['prevEducation'].replace(educstd)
data['prevEducation'].unique()

<StringArray>
['Masters', 'Diploma', 'High School', 'Bachelors', 'Doctorate']
Length: 5, dtype: str

In [21]:
# Convert score-related columns from integer
# to float data types for consistency.

data.dtypes
data['entryEXAM'] = data['entryEXAM'].astype('float64')
data['Python'] = data['Python'].astype('float64')
data['DB'] = data['DB'].astype('float64')
data.dtypes

fNAME                str
lNAME                str
Age                int64
gender               str
country              str
residence            str
entryEXAM        float64
prevEducation        str
studyHOURS         int64
Python           float64
DB               float64
dtype: object

In [22]:
# Rename columns using a cleaner naming convention
# and create a FullName column for better readability.

data.columns #fNAME', 'lNAME', 'Age', 'gender', 'country', 'residence', 'entryEXAM', 'prevEducation', 'studyHOURS', 'Python', 'DB'
data = data.rename(columns={'fNAME':'FirstName',
    'lNAME':'LastName',
    'gender':'Gender',
    'country':'Country',
    'residence':'Residence',
    'entryEXAM':'EntryExam',
    'prevEducation':'PrevEducation',
    'studyHOURS':'StudyHours'})
data['FullName'] = data['FirstName'] + ' ' + data['LastName']
data.insert(2,'FullName', data.pop('FullName'))

data.head()

,FirstName,LastName,FullName,Age,Gender,Country,Residence,EntryExam,PrevEducation,StudyHours,Python,DB
0,Christina,Binger,Christina Binger,44,Female,Norway,Private,72.0,Masters,158,59.00,55.0
1,Alex,Walekhwa,Alex Walekhwa,60,Male,Kenya,Private,79.0,Diploma,150,60.00,75.0
2,Philip,Leo,Philip Leo,25,Male,Uganda,Sognsvann,55.0,High School,130,74.00,50.0
3,Shoni,Hlongwane,Shoni Hlongwane,22,Female,South Africa,Sognsvann,40.0,High School,120,75.85,44.0
4,Maria,Kedibone,Maria Kedibone,23,Female,South Africa,Sognsvann,65.0,High School,122,91.00,80.0

In [23]:
# Before exporting the cleaned dataset for SQL analysis,
# identify and handle potential outliers.

# Validate potential outliers in Age and score-related columns.
# Expected age values should range between 20 and 60 years,
# while score values should remain within valid academic ranges.

data['Age'].sort_values() #Index 55 and 32 must be replaced with average age
data.loc[[55,32], 'Age']=data['Age'].mean().astype('int')
data.loc[55, 'Age']

data['EntryExam'].sort_values() # No anomalies detected.
data['Python'].sort_values() # No anomalies detected.
data['DB'].sort_values() # No anomalies detected.
data

,FirstName,LastName,FullName,Age,Gender,Country,Residence,EntryExam,PrevEducation,StudyHours,Python,DB
0,Christina,Binger,Christina Binger,44,Female,Norway,Private,72.0,Masters,158,59.00,55.0
1,Alex,Walekhwa,Alex Walekhwa,60,Male,Kenya,Private,79.0,Diploma,150,60.00,75.0
2,Philip,Leo,Philip Leo,25,Male,Uganda,Sognsvann,55.0,High School,130,74.00,50.0
3,Shoni,Hlongwane,Shoni Hlongwane,22,Female,South Africa,Sognsvann,40.0,High School,120,75.85,44.0
4,Maria,Kedibone,Maria Kedibone,23,Female,South Africa,Sognsvann,65.0,High School,122,91.00,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...
72,Clara,Bernard,Clara Bernard,43,Female,France,Private,80.0,Bachelors,150,75.00,43.0
73,Julian,Nielsen,Julian Nielsen,31,Male,Denmark,Sognsvann,90.0,Masters,158,84.00,83.0
74,Sophie,Brown,Sophie Brown,33,Female,United Kingdom,Sognsvann,96.0,Masters,158,85.00,90.0
75,Leon,Bauer,Leon Bauer,35,Male,Germany,Sognsvann,90.0,Masters,160,87.00,74.0
76,Mohammed,Salim,Mohammed Salim,31,Male,Somalia,Sognsvann,35.0,Masters,144,72.00,90.0

In [24]:
# Export the cleaned dataset for SQL analysis.

data.to_csv(
    r'C:\Users\IngBiomedica\Desktop\CleanedBI.csv',
    index=False
)